batch_size: 30
beta1: 0.75
cs: 184
loss_cs: 184  # Center crop for the loss function. Should be bigger when g_network is not UNet.
min_crop_size: null  # This triggers a dataset check.
g_network: UtNet
start_epoch: 1
threads: 8  # For the data loader. Adjust as available.
time_limit: null
train_data:
- ../../datasets/cropped/NIND_256_192
models_dpath: ../../models/nind_denoise
validation_interval: 1
orig_data: ../../datasets/NIND
g_funit: 64
g_lr: 0.0001